### ISSUE TITLE
Remediation Source field: cannot get to the bottom

### ISSUE THREAD

**Issue by JenM00re** [Swarthmore/emma-metadata-enhancer#6]
Cannot get to the bottom of the list to access "other" or "another DSO" because I can't scroll down to expand the page.

**Comment by devnoot** [comment]
The left (main) section of the webapp is a scroll area. My guess is that your mouse was on the right side of the webapp while you tried this. Can you confirm that this is the case?

With that said -- I did notice that the scrollbar only appears if your mouse is in the scroll area, so perhaps that can be changed.

**Comment by JenM00re** [comment]
I recorded a video (sorry, no sound, but I did use bookmarks to help guide you if you view it in Panopto).

I used various means of entry to the list, but the bottom of the list is not viewable.

[EMMA Metadata enhancer: Remediation Source list not viewable](https://swarthmore.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0f5892af-e646-4d4f-97fe-b17200dcab7f)

**Comment by devnoot** [comment]
I will look. I just verified it works in Firefox, so perhaps it's a browser thing.
